crtfile: /tmp/ssl.crt  # Public Certificate file (created if needed)
keyfile: /tmp/ssl.key  # Private Key file (created if needed)

key_size: 4096  # RSA key size 
digest: sha256  # digest type (https://www.openssl.org/docs/manmaster/apps/openssl.html)
crt_renew: True   # Renew public cert if expired
crt_renew_force: True    # force renew cert on every playbook run
crt_days_valid: 365     # Days for cert to be valid
crt_cn: domain.com      # Common/Domain name
crt_o: My Company Name  # Org Name
crt_c: CA       # Country

key_user: root 
key_group: root
key_mode: 0600

file_override: False   # Force overwrite if cert/key already exists. True or False
