---
- name: Install tomcat
  yum: name="tomcat" state="present"
  tags: tomcat

- name: "Set TZ variable in tomcat's init-environment"
  lineinfile:
    dest: "{{ tomcat.config_file }}"
    line: "TZ=\"{{ timezone }}\""
    state: present
    create: no
  notify: restart tomcat
  tags: tomcat

- name: Add AJP to connect to Apache
  copy: src={{ item }} dest=/etc/httpd/conf.d/{{ item }}
  with_items:
    - ajp.conf
  notify: restart tomcat

- debug: var=ldap_grouper_user

- name: Create directory for application config
  file: state=directory path={{ tomcat_install_dir }}/{{ tomcat_properties_dir }} owner=tomcat group=tomcat
  tags: tomcat

- name: Create directory for wars
  file: state=directory path={{ tomcat_install_dir }}/wars owner=tomcat group=tomcat
  tags: tomcat

- name: "DEPRECATED: Create shared directory for jars"
  file: state=directory path={{ tomcat_share_dir }}/shared owner=tomcat group=tomcat
  notify: restart tomcat
  tags: tomcat

- name: "DEPRECATED: Create shared lib directory for jars"
  file: state=directory path={{ tomcat_share_dir }}/shared/lib owner=tomcat group=tomcat
  notify: restart tomcat
  tags: tomcat

- name: Copy tomcat config
  template: src={{ item }}.j2 dest={{ tomcat_install_dir }}/{{ item }}
  with_items:
    - catalina.properties
    - tomcat-users.xml
  notify: restart tomcat
  tags: tomcat

- name: Copy tomcat 7 specific config
  template: src=server_tomcat7.xml.j2 dest={{ tomcat_install_dir }}/server.xml
  notify: restart tomcat
  tags: tomcat

- name: Copy sysconfig tomcat
  template: src=tomcat6.conf.j2 dest={{ tomcat_install_dir }}/tomcat6.conf
  notify: restart tomcat
  tags: tomcat

- name: Unused webapps dir must still be present
  file: path={{ tomcat.lib_dir }}/webapps state=directory group=tomcat owner=tomcat
  tags: tomcat

- include: java_keystore.yml
  when: env == 'vm' or
        env == 'vm-centos7'

- name: Make sure Tomcat starts when the system is booted.
  service: name={{ tomcat.service_name }} enabled=yes
