- name: Copy certbot auto
  copy:
    src=files/certbot-auto
    dest=/root/certbot-auto
    mode=0744

- name: Run certbot-auto dependencies
  command: /root/certbot-auto -nq plugins
  register: cb_reg
  changed_when: cb_reg.rc != 0

- name: Run certbot-auto for virtual environment (needed to patch python libs)
  command: /root/certbot-auto certonly --standalone --agree-tos --dry-run -n
  ignore_errors: yes

- name: Patch certbot with ipv6 patch
  patch:
    src=files/certbot_ipv6.patch
    basedir=/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme
    strip=3

- name: Make sure webroot certbot directory exists
  file: path={{ dokuwiki_dir }} state=directory

- name: Create certbot certs if needed
  command: /root/certbot-auto certonly \
          --standalone \
          --agree-tos \
          --email {{ dokuwiki_email }} \
          --keep-until-expiring \
          --expand
          --quiet \
          -n \
          -d {{ dokuwiki_domain }} \
          --pre-hook "service apache2 stop" --post-hook "service apache2 start" \
          --webroot-path={{ dokuwiki_dir }}

- name: Setup certbot crontab if needed
  cron: name="Autorenew certbot"
        minute="8" hour="0,12"
        job="/root/certbot-auto renew --quiet --keep-until-expiring --webroot-path={{ dokuwiki_dir }} --pre-hook 'service apache2 stop' --post-hook 'service apache2 start'"
        cron_file=certbot
        user="root"
