- name: download release
  get_url:
    url: "{{ maven_repo }}/{{ springapp_artifact_group_dir }}/{{ springapp_artifact_id }}/{{ springapp_version }}/{{ springapp_artifact_id }}-{{ springapp_version }}.{{ springapp_artifact_type }}"
    dest: "{{ springapp_dir }}/{{ springapp_artifact_id }}-{{ springapp_version }}.{{ springapp_artifact_type }}"
    owner: "{{ springapp_user }}"
    group: "{{ springapp_user }}"
  register: springapp_release_released

- include: switch-version.yml springapp_released={{ springapp_release_released }}
  when: springapp_release_released.changed
