- name: download snapshot
  get_url:
    url: "{{ maven_snapshot_repo }}{{ springapp_artifact_group_dir }}/{{ springapp_artifact_id }}/{{ springapp_version }}-SNAPSHOT/{{ springapp_artifact_id }}-{{ springapp_version }}-{{ springapp_snapshot_timestamp }}.{{ springapp_artifact_type }}"
    dest: "{{ springapp_dir }}/{{ springapp_artifact_id }}-{{ springapp_version }}-{{ springapp_snapshot_timestamp }}.{{ springapp_artifact_type }}"
    owner: "{{ springapp_user }}"
    group: "{{ springapp_user }}"
  register: springapp_snapshot_released

- include: switch-version.yml springapp_released={{ springapp_snapshot_released }}
  when: springapp_snapshot_released.changed
