---
dependencies:
- { role: get_grouper, grouper_dist_version: 4.0.0 }
- { role: tomcat_app
  , app_name: grouper
  , app_version: "2.1.5"
  , app_snapshot_timestamp: ""
  , app_local_war: "{{ role_path }}/../get_grouper/files/tomcat/webapps/grouper-ui-2.1.5.war"
  , app_group_url: ""
  , app_artifact_id: ""
  , deploy_name: grouper
  , deploy_xml_name: grouper
  , tomcat_context_path: /grouper
  , tomcat_handler_name: tomcat
  , tags: grouper }
- { role: tomcat_app
  , app_name: grouper
  , app_version: "2.1.5"
  , app_snapshot_timestamp: ""
  , app_local_war: "{{ role_path }}/../get_grouper/files/tomcat/webapps/grouper-ws-2.1.5.war"
  , app_group_url: ""
  , app_artifact_id: ""
  , deploy_name: grouper-ws
  , deploy_xml_name: grouper-ws
  , tomcat_context_path: /grouper-ws
  , tomcat_handler_name: tomcat
  , tags: grouper }
