---
galaxy_info:
  author: Andrew Klaus (Cybera)
  description: Configures SimpleSAMLphp as an IdP
  license: GPLv2
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - web
dependencies:
  - ssp_install
