---
- name: Set hosts
  lineinfile: dest=/etc/hosts line="{{ hosts_ip_address }} {{ item }}"
  with_items:
    - "static.vm.openconext.org"
    - "serviceregistry.vm.openconext.org"
    - "engine.vm.openconext.org"
    - "profile.vm.openconext.org"
    - "mujina-sp.vm.openconext.org"
    - "mujina-idp.vm.openconext.org"
    - "grouper.vm.openconext.org"
    - "authz.vm.openconext.org"
    - "authz-admin.vm.openconext.org"
    - "voot.vm.openconext.org"
    - "authz-playground.vm.openconext.org"
    - "lb.vm.openconext.org"
    - "apps.vm.openconext.org"
    - "ldap.vm.openconext.org"
    - "db.vm.openconext.org"
    - "pdp.vm.openconext.org"
    - "engine-api.vm.openconext.org"
    - "aa.vm.openconext.org"
    - "multidata.vm.openconext.org"
    - "oidc.vm.openconext.org"
    - "teams.vm.openconext.org"
