---
- name: Download current version
  get_url: url="{{ profile_download_url }}" dest="{{ profile_build_path }}"
  register: profile_download

- name: Unpack current version
  unarchive: src={{ profile_build_path }} dest={{ openconext_releases_dir }} copy=no
  when: profile_download.changed

- set_fact: profile_install_dir="{{ profile_release_dir }}"
