---
- name: copy mujina-idp configuration
  template: src=mujina-idp.properties.j2 dest={{ tomcat.install_dir }}/{{ tomcat.properties_dir }}/mujina-idp.properties
  tags: mujina-idp
  notify: restart tomcat

- name: copy mujina-idp logging configuration
  copy: src=mujina-idp-logback.xml dest={{ tomcat.install_dir }}/{{ tomcat.properties_dir }}/mujina-idp-logback.xml group=tomcat owner=tomcat
  tags: mujina-idp
  notify: restart tomcat

- name: copy virtual host config
  template: src=mujina-idp.conf.j2 dest=/etc/httpd/conf.d/mujina-idp.conf
  tags: mujina-idp
  notify: reload httpd

- include: provision_grouper.yml source_id="openconext-ldap"
