---

- name: restart iptables
  service: name=iptables state=restarted

- name: restart ip6tables
  service: name=ip6tables state=restarted

- name: restart journald
  service: name=systemd-journald state=restarted

- name: rebuild sendmail config
  shell: "make -C /etc/mail && service sendmail restart"
