#---
## Version of EngineBlock that is installable by this role
engine_version: ''
#engine_branch: "develop"

# Feature toggles
engine_feature_ldap_integration: 1
engine_feature_encrypted_assertions: 1
engine_feature_encrypted_assertions_require_outer_signature: 1
engine_feature_run_all_manipulations_prior_to_consent: 0

engine_api_feature_metadata_push: 1
engine_api_feature_consent_listing: 1
engine_api_feature_metadata_api: 1

# Cutoff point for showing unfiltered IdPs on the WAYF
engine_wayf_cutoff_point_for_showing_unfiltered_idps: 50

## Engine installer specific variables.
engine_version_dir: "{{ engine_version | replace('/', '-') }}"
engine_branch_dir: "{{ openconext_builds_dir }}/OpenConext-engineblock-{{ engine_branch | replace('/', '-') }}"
engine_release_dir: "{{ openconext_releases_dir }}/OpenConext-engineblock-{{ engine_version_dir }}"
engine_build_path: "{{ openconext_builds_dir }}/OpenConext-engineblock-{{ engine_version_dir }}.tar.gz"
engine_download_url: "https://github.com/OpenConext/OpenConext-engineblock/releases/download/{{ engine_version }}/OpenConext-engineblock-{{ engine_version_dir }}.tar.gz"
engine_current_release_symlink: "{{ openconext_releases_dir }}/OpenConext-engineblock"

engine_ipv4_address: "*"
# engine_ipv6_address:
engine_api_ipv4_address: "*"
# engine_api_ipv6_address:

# Required for the Symfony routing.
engine_base_domain: "{{ base_domain }}"

engine_domain: engine.{{ base_domain }}
engine_api_domain: engine-api.{{ base_domain }}

engine_debug: false

## The endpoint it can use to validate Virtual Organizations
engine_vovalidate_baseurl : https://api.{{ base_domain }}

## PDP endpoint
engine_pdp_baseurl: https://pdp.{{ base_domain }}/pdp/api/decide/policy

## Attribute Aggregation endpoint
engine_attribute_aggregation_baseurl: "https://aa.{{ base_domain }}/aa/api/attribute/aggregate"
engine_attribute_aggregation_username: "{{ aa.eb_username }}"
engine_attribute_aggregation_password: "{{ aa.eb_password }}"

## Where EngineBlock can go for its (v1) Service Registry API
engine_janus_url: https://serviceregistry.{{ base_domain }}/simplesaml/module.php/janus/services/rest/
engine_janus_cache_lifetime: 3600 # Cache for an hour

engine_api_janus_user: serviceregistry
engine_api_janus_password: secret
engine_api_profile_user: profile
engine_api_profile_password: secret

engine_engine_idp_baseurlpath: "https://{{ engine_domain }}/simplesaml/"

# Minimum execution time in milliseconds when a received response is deemed invalid
engine_minimum_execution_time_on_invalid_received_response: 5000

## The priority of messages that should be logged to syslog
## 7 = debug
## 6 = notices
engine_syslog_priority: 7

#engine_initial_sql: ''

engineblock_symfony_cache_path: "/tmp/engineblock/cache"
engineblock_symfony_log_path: "/tmp/engineblock/log"

engine_fpm_user: engine
engine_fpm_port: 801
