---
keytool:
  current_certificates:
   - { alias: "openconext cacert CA", file: "{{ tls.cert_path_ca }}/{{ tls_ca }}" }
  # revoked_certificates contains a list of aliases of certificates that must be revoked.
  # You can not reuse alias names.
  # revoked_certificates:
  #   - "alias to revoke"

tomcat_install_dir: "{{ tomcat.install_dir }}"
tomcat_properties_dir: "{{ tomcat.properties_dir }}"
tomcat_share_dir: "{{ tomcat.share_dir }}"
tomcat_service_name: "{{ tomcat.service_name }}"
